1. 使用letcc/throw实现call-with-current-continuation, 基于5_42

直接在5_42里运行
```scheme
   (eopl:pretty-print (run
   " 
   let call-with-current-continuation
   = proc (p)
      letcc cont 
      in (p proc (v) 
              throw v to cont)
   in let f1 = proc (g) 
                 (g 10)
      in (call-with-current-continuation f1)
   "
   ))
```

2. 不实现letcc/throw, 直接实现callcc, 基于ch5/p174_exception

```scheme
x绑定到callcc的cont上, 本质和1的x绑定到proc (v) throw v to cont是一样的, 虽然实现的方式不一样
用2这种方式感觉更好, x直接被绑定在了callcc的continuation上
```


---


考虑下面这个例子:
```scheme
考虑下面这个例子:
    "-(3, callcc(proc (x) (x 100)))"
在value-of/k (proc-exp)得到proc-val后
调用这个proc-val, 即:
(apply-procedure proc1 
                 (cont-val saved_cont)
                 saved_cont)
(define apply-procedure
  (lambda (proc1 arg cont)
    (cases proc proc1
      (procedure (var body saved_env)
        (value-of/k body 
                    (extend-env (list var) 
                                (list arg)
                                saved_env)
                    cont)))))
saved_cont是call-exp的contination
然后value-of/k (call-exp x 100) env(里面有cont-val) cont(这个cont和env里的cont是同一个)
经过
call-exp的cont -> (rator-cont (rand saved_env saved_cont)) -> (rand-cont (rator saved_cont))
到达:
        (rand-cont (rator saved_cont)
          (cases expval rator
            (proc-val (proc1)
              (apply-procedure proc1 val saved_cont))
            (cont-val (cont1)  ; 在这种情况下可以忽略掉saved_cont, 因为cont-val里有continuation
              (apply-cont cont1 val))  ;用的是env里的cont, 从rator来, rator从env里找到
            (else eopl:error "rator not proc or cont")))
```